name: 'Pull request summarizer'
description: 'Write a comment about every commit in a pull request, every file diff, and summarize PR'
inputs:
  repository:
    description: 'The repository that the pull request is being opened in'
    required: true
    default: ''
  token:
    description: 'The GitHub token to use for authenticating the action'
    required: true
    default: ''
  openai_model:
    description: "The used for summarization, full list here: https://platform.openai.com/docs/models/overview"
    required: false
    default: "gpt-3.5-turbo"
  ignore_files:
    description: "A list of glob pattens to ignore when summarizing, separated by commas, e.g. *.lock,*.lock.json"
    required: false
    default: "*.lock,*lock.json,*lock.yaml,*lock.yml"
branding:
    icon: 'aperture'
    color: 'purple'
runs:
  using: 'node20'
  main: 'lib/index.js'
