name: 'Pull request summarizer'
description: 'Write a comment about every commit in a pull request, every file diff, and summarize PR'
inputs:
  repository:
    description: 'The repository that the pull request is being opened in'
    required: true
    default: ''
  token:
    description: 'The GitHub token to use for authenticating the action'
    required: true
    default: ''
branding:
    icon: 'aperture'
    color: 'purple'
runs:
  using: 'node16'
  main: 'lib/index.js'
