name: Setup Node

runs:
  using: "composite"
  steps:
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: |
          ./node_modules
          ./.eslintcache
          ./.npm
          ~/.npm
        key: ${{ runner.os }}-npm-${{ github.repository }}-v1-${{ hashFiles('./yarn.lock') }}
        restore-keys: ${{ runner.os }}-npm-${{ github.repository }}-v1-

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "16"

    - name: Install dependencies - Node
      shell: bash
      run: |
        FORCE_COLOR=true yarn install --frozen-lockfile
