name: Pull Request - Node
on:
  push:
    branches-ignore:
      - "gh-pages"

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: ./.github/workflows/setup-node

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: ./.github/workflows/setup-node

      - name: Lint
        run: |
          yarn lint

      - name: Node Audit
        run: |
          # Avoid failing the pipeline, just report the issues
          yarn audit --audit-level=critical || true

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: ./.github/workflows/setup-node

      - id: auth
        uses: google-github-actions/auth@v1
        with:
          export_environment_variables: true
          credentials_json: "${{ secrets.GCR_JSON }}"

      - name: Test
        run: |
          yarn test
        env:
          PROJECT_ID: ${{ steps.auth.outputs.project_id}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  code-analysis:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          config-file: ./.github/codeql/codeql-config.yml
          languages: "javascript"

      - uses: ./.github/workflows/setup-node

      - name: Build
        run: |
          yarn build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"
